# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-06 23:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=140)),
                ('is_urgent', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(verbose_name='Date Published')),
                ('exp_date', models.DateTimeField(verbose_name='Expiry Date')),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('last_update', models.DateTimeField(verbose_name='Last Update')),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('description', models.CharField(max_length=140)),
                ('pub_date', models.DateTimeField(verbose_name='Date Published')),
                ('file', models.FileField(upload_to=main.models.section_upload_path)),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Lecturer')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Folder')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=140)),
            ],
        ),
        migrations.AddField(
            model_name='folder',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Lecturer'),
        ),
        migrations.AddField(
            model_name='folder',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Section'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Lecturer'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Section'),
        ),
    ]
